package com.portal.tftteambuilderproject.utilities.helper

import com.portal.tftteambuilder.R

class Util {

    enum class Champion(val championName: String, val imagePath: Int) {
        ANNIE("Annie", R.drawable.annie),
        CORKI("Corki", R.drawable.corki),
        AHRI("Ahri", R.drawable.ahri),
        AKALI_KDA("Akali K/DA", R.drawable.akali_kda),
        AMUMU("Amumu", R.drawable.amumu),
        AKALI_TRUEDAMAGE("Akali True Damage", R.drawable.akali_truedamage),
        APHELIOS("Aphelios", R.drawable.aphelios),
        BARD("Bard", R.drawable.bard),
        BLITZCRANK("Blitzcrank", R.drawable.blitzcrank),
        CAITLYN("Caitlyn", R.drawable.caitlyn),
        EKKO("Ekko", R.drawable.ekko),
        EVELYNN("Evelynn", R.drawable.evelynn),
        GAREN("Garen", R.drawable.garen),
        GNAR("Gnar", R.drawable.gnar),
        GRAGAS("Gragas", R.drawable.gragas),
        EZREAL("Ezreal", R.drawable.ezreal),
        KARTUSH("Kartush", R.drawable.kartush),
        ILLAOI("Illaoi", R.drawable.illaoi),
        KAYN("Kayn", R.drawable.kayn),
        SERAPHINE("Seraphine", R.drawable.seraphine),
        NEEKO("Neeko", R.drawable.neeko),
        ZAC("Zac", R.drawable.zac),
        KAYLE("Kayle", R.drawable.kayle),
        LUCIAN("Lucian", R.drawable.lucian),
        NAMI("Nami", R.drawable.nami),
        SAMIRA("Samira", R.drawable.samira),
        JINX("Jinx", R.drawable.jinx),
        YORICK("Yorick", R.drawable.yorick),
        VIEGO("Viego", R.drawable.viego),
        KAI_SA("Kai'sa", R.drawable.kaisa),
        LUX("Lux", R.drawable.lux),
        SONA("Sona", R.drawable.sona),
        RIVEN("Riven", R.drawable.riven),
        PANTHEON("Pantheon", R.drawable.pantheon),
        POPPY("Poppy", R.drawable.poppy),
        MORDEKAISER("Mordekaiser", R.drawable.mordekaiser),
        TWISTED_FATE("Twisted Fate", R.drawable.twistedfate),
        JAX("Jax", R.drawable.jax),
        OLAF("Olaf", R.drawable.olaf),
        K_SANTE("KSante", R.drawable.ksante),
        THRESH("Thresh", R.drawable.thresh),
        KENNEN("Kennen", R.drawable.kennen),
        TWITCH("Twitch", R.drawable.twitch),
        LULU("Lulu", R.drawable.lulu),
        MISS_FORTUNE("Miss Fortune", R.drawable.missfortune),
        KARTHUS("Karthus", R.drawable.kartush),
        SENNA("Senna", R.drawable.senna),
        VI("Vi", R.drawable.vi),
        TAHM_KENCH("Tahm Kench", R.drawable.tahmkench),
        URGOT("Urgot", R.drawable.urgot),
        TARIC("Taric", R.drawable.taric),
        YONE("Yone", R.drawable.yone),
        JHIN("Jhin", R.drawable.jhin),
        QIYANA("Qiyana", R.drawable.qiyana),
        KATARINA("Katarina", R.drawable.katarina),
        ZED("Zed", R.drawable.zed),
        LILLIA("Lillia", R.drawable.lillia),
        VEX("Vex", R.drawable.vex),
        ZIGGS("Ziggs", R.drawable.ziggs),
        YASUO("Yasuo", R.drawable.yasuo),
        SETT("Sett", R.drawable.sett)
    }
}